---
title: "Notas de repaso: **MARKDOWN**"
subtitle: "Microestructura y Sistemas de Trading"
author: "franciscome@iteso.mx"
date: "January 15, 2018"
output: html_document
---

Este documento contiene algunas notas y comandos útiles respecto a **markdown**.

### Headers de chunks para R

Se usan 3 *acentos inversos* para indicar que es un *chunk* o pedazo de código. En éste ejemplo se usaron 3 *apostrofes* para ilustrar, el caracter indicado son *acentos inversos* ```:

<pre>'''{r nombre_chunk}
codigo
codigo
'''
</pre>

### Opciones para headers de chunks

- **echo=FALSE** : Oculta el código en el documento final, pero si muestra cualquier resultado o mensaje de salida.
- **results="hide"** : Oculta resultados y mensajes de salida, pero el código si será mostrado.
- **include=FALSE ** : Se corre el código del chunk, pero el código, resultados y imagenes no se incluyen en documento final.
- **fig.show="hide"** : Oculta imagenes generadas dentro del chunk.
- **fig.width** : Para modificar el ancho de la imagen de salida. Puede ser pulgadas (in), centímetros (cm)
- **fig.height** : Para modificar el alto de la imagen de salida.
- **warning=FALSE** : Suprime cualquier warning de consola.
- **message=FALSE ** : Suprime cualquier mensaje de consola.

### Código sobre linea de escritura

para poder mandar llamar un pedazo de código dentro de la misma linea de escritura de texto sólo hay que colocar un *acento inverso* la letra *r* seguido del comando a ejecutar y cerrando de nuevo con un *acento inverso*. 

<pre>
'r cor(x,y)'
</pre>

###  Opciones globales para chunks

Se puede hacer un chunk especial que indique las opciones globales por default de todos los demás chunks utilizados. 

<pre>
'''{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, echo=FALSE, warning=FALSE, message=FALSE)
'''
</pre>

### Opciones de paquete knitr

<pre>
'''{r package_options, include=FALSE}
knitr::opts_knit$set(progress = TRUE, verbose = TRUE)
options("scipen"=100, "digits"=4)
'''
</pre>

### Mas información de **Markdown**

Puedes encontrar mas información en estos sitios:

- [Cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
- [GitHub Guides](https://guides.github.com/features/mastering-markdown/)
- [Video corto: Roger Peng](https://www.youtube.com/watch?v=DNS7i2m4sB0)
- [Video extenso: Ahmed Hasan](https://www.youtube.com/watch?v=MIlzQpXlJNk)
