
\documentclass[final, xcolor=table]{beamer}
\usetheme{myst}
\usepackage[orientation=portrait,size=a0,scale=1.4]{beamerposter}
\usepackage{graphicx}
\usepackage{booktabs  }
\usepackage[spanish]{babel}
\usepackage{amsmath,amsthm,amssymb,latexsym}
\usepackage{booktabs}
\usepackage{ragged2e}
\graphicspath{{figures/}}

<<Ini, include=FALSE, echo=FALSE, eval=TRUE>>=

# -- ----------------------------------------------------------------------------------------- -- #
# -- Inicializador general de sistema ------------------------------------------------ ETAPA 0 -- #
# -- ----------------------------------------------------------------------------------------- -- #

# -- Remover Objetos de Environment
rm(list=ls())

# -- Separador de miles
knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})

# -- ------------------------------------------------------------------------------- ETAPA 0.0 -- #
# -- --------------------------------------------------------------------- Paquetes a utilizar -- #

pkg <- c("downloader","dplyr","fBasics","gridExtra","ggplot2","httr","jsonlite","lubridate",
         "lattice","moments","matrixStats", "plyr","plotly","plot3D", "reshape2","RCurl", "stats", 
         "scales", "tseries","XML","xts","xlsx","xtable","zoo")

# -- Instalar y/o cargar paquetes necesarios-
inst <- pkg %in% installed.packages()
if(length(pkg[!inst]) > 0)
  install.packages(pkg[!inst], repo='https://cran.cnr.Berkeley.edu/')
instpackages <- lapply(pkg, library, character.only=TRUE)

# -- ------------------------------------------------------------------------------- ETAPA 0.1 -- #
# -- ------------------------------------------------- Variables de etorno y objetos generales -- #

# -- Huso horario
Sys.setenv(tz="America/Guadalajara")
options(tz="America/Guadalajara")

Sys.setenv(TZ="America/Guadalajara")
options(TZ="America/Guadalajara")

@

% -- -------------------------------------------------------------------------------------------- %
%	-- TITLE SECTION 
% -- -------------------------------------------------------------------------------------------- %

\title{\Huge Back Test Algoritmo A01}
\institute{\Large Box Jenkins para series de tiempo financieras}

% -- -------------------------------------------------------------------------------------------- %
%	-- FOOTER TEXT
% -- -------------------------------------------------------------------------------------------- %

\newcommand{\leftfoot}{Official Web Page:}
\newcommand{\rightfoot}{More Info: }

% -- -------------------------------------------------------------------------------------------- %
\begin{document}

\title{Back Test Algor\'itmo A01}
\begin{frame}

% -- ----------------------------------------------------------------------------------------- -- %
% -- -- Informacion del Activo -- VELAS ------------------------------------------------------ -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{columns}[t]

% -- ------------------------------------------------------------------------------- Columna 1 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.66 \linewidth}

  \begin{block}{\small Precio de Cierre: } : 
  \textit{Texto}

    % \begin{figure}[H]
    % \includegraphics[scale=1]{figure/G0_HistoricoPrecios-1.pdf}
    % \end{figure}

  \end{block}
  
\end{column}

% -- ------------------------------------------------------------------------------- Columna 2 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.32 \linewidth}
\begin{block}{\small Estad\'istica Precios (Velas) hist\'oricas}

  Tabla

\end{block}
\end{column}

\end{columns}

% -- ----------------------------------------------------------------------------------------- -- %
% -- -- Informacion del Activo -- Velas A ---------------------------------------------------- -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{columns}[t]

% -- ------------------------------------------------------------------------------- Columna 1 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.24 \linewidth}

  \begin{block}{\small {Price.Open - Price.Low}}

    % \begin{figure}[H]
    % \includegraphics[scale=1]{figure/G1A_HistoricoVelas-1.pdf}
    % \end{figure}

  \end{block}

\end{column}

% -- ------------------------------------------------------------------------------- Columna 2 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.24 \linewidth}

  \begin{block}{\small {Price.High - Price.Open}}

    % \begin{figure}[H]
    % \includegraphics[scale=1]{figure/G1A_HistoricoVelas-2.pdf}
    % \end{figure}

  \end{block}
  
\end{column}

% -- ----------------------------------------------------------------------------------------- -- %
% -- -- Informacion del Activo -- Velas B ---------------------------------------------------- -- %
% -- ----------------------------------------------------------------------------------------- -- %

% -- ------------------------------------------------------------------------------- Columna 1 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.24 \linewidth}

  \begin{block}{\small {Price.Close - Price.Open}}

    % \begin{figure}[H]
    % \includegraphics[scale=1]{figure/G1A_HistoricoVelas-3.pdf}
    % \end{figure}

  \end{block}
  
\end{column}

% -- ------------------------------------------------------------------------------- Columna 2 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.24 \linewidth}

  \begin{block}{\small {Price.High - Price.Low}}

    % \begin{figure}[H]
    % \includegraphics[scale=1]{figure/G1A_HistoricoVelas-4.pdf}
    % \end{figure}

  \end{block}
  
\end{column}


\end{columns}

% -- ----------------------------------------------------------------------------------------- -- %
% -- -- Informacion del Algoritmo ------------------------------------------------------------ -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{columns}[t]

% -- ------------------------------------------------------------------------------- Columna 1 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.32 \linewidth}

\begin{block}{\small Descripci\'on}
\justify{Metodolg\'ia \textit{BoxJenkins} para series de tiempo}
\end{block}
\end{column}

% -- ------------------------------------------------------------------------------- Columna 2 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.32 \linewidth}
\begin{block}{\small Datos Entrada}
\small
\textbf{Par\'ametros de Entrada}

% \begin{itemize}
%   \item Tama\~no de Ventana de informaci\'on: 
%   \item Noci\'on de par\'ametro info:
%   \item L\'ogica de Aplicaci\'on de Algor\'itmo:
%   \item Instrumento a Utilizar: 
%   \item Periodicidad de precios:
%   \item Valores de Exploraci\'on.
%   \end{itemize}

\end{block}
\end{column}

% -- ------------------------------------------------------------------------------- Columna 3 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.32 \linewidth}
\begin{block}{\small Datos Salida}
\small
\textbf{Par\'ametros de Salida}

\begin{itemize}
  \item Predicci\'on del signo del rendimiento
  \item Take Profit
  \item Stop Loss
\end{itemize}

\end{block}
\end{column}

\end{columns}

% -- ----------------------------------------------------------------------------------------- -- %
% -- -- Informacion del desempeno de Algoritmo ----------------------------------------------- -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{columns}[t]

% -- ------------------------------------------------------------------------------- Columna 1 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.32 \linewidth}
\begin{block}{\small Desempe\~no de los 4 mejores casos}


\small
\begin{itemize}
  \item Criterio 1: Con mayor profit final acumulado.
  \item Criterio 2: Con menor DrawDown registrado.
  \item Criterio 3: Con menor registro de minusval\'ia general.
  \item Criterio 4: Mayor Exito en Trading.
\end{itemize}

\end{block}
\end{column}

% -- ------------------------------------------------------------------------------- Columna 3 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.66 \linewidth}
\begin{block}{\small Pips Acumulados para cada Variaci\'on de Par\'ametros}

  % \begin{figure}[H]
  %   \includegraphics[scale=1]{figure/G2_ProfitAcumulada-1.pdf}
  % \end{figure}
  
\end{block}
\end{column}

\end{columns}

% -- ----------------------------------------------------------------------------------------- -- %
% -- -- Perdedoras Consecutivas y Ganadoras Consecutivas ------------------------------------- -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{columns}[t]

% -- ------------------------------------------------------------------------------- Columna 1 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.24 \linewidth}
\begin{block}{\small Tabla Gc Vs Pc }

  % \small
  % \centering
  % \Sexpr{kable(Tabla_PcGc[[1]], align = "c")}

\end{block}
\end{column}

% -- ------------------------------------------------------------------------------- Columna 2 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.24 \linewidth}
\begin{block}{\small Tabla Gc Vs Pc }

  % \small
  % \centering
  % \Sexpr{kable(Tabla_PcGc[[2]], align = "c")}

\end{block}
\end{column}

% -- ------------------------------------------------------------------------------- Columna 3 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.24 \linewidth}
\begin{block}{\small Tabla Gc Vs Pc }

  % \small
  % \centering
  % \Sexpr{kable(Tabla_PcGc[[3]], align = "c")}

\end{block}
\end{column}

% -- ------------------------------------------------------------------------------- Columna 4 -- %
% -- ----------------------------------------------------------------------------------------- -- %

\begin{column}{.24 \linewidth}
\begin{block}{\small Tabla Gc Vs Pc }

  % \small
  % \centering
  % \Sexpr{kable(Tabla_PcGc[[4]], align = "c")}

\end{block}
\end{column}

\end{columns}
\end{frame}

\end{document}
