---
title: "Notas de repaso: **R**"
subtitle: "Microestructura y Sistemas de Trading"
author: "franciscome@iteso.mx"
date: "January 15, 2018"
output: html_document
---

### Instalar/Cargar paquetes

```{r Instalar, message=FALSE, warning=FALSE}

# Vector con el nombre de los paquetes a utilizar
pkg <- c("base","readxl","xts","zoo")

# Solicitar los paquetes instalados en la computadora
# utilizar el operador %in% para verificar cuales de los paquetes, dentro de "pkg" estan instalados
# se guardara vector lógico, TRUE (instalados) o FALSE (no instalados) de la misma longitud que "pkg"
instalados <- pkg %in% installed.packages()

# si hay, cuando menos 1 paquete no instalado, se tendrá un TRUE Y se usará para seleccionar de "pkg"
# se instala en caso de no contar con el o sólo se carga en caso de si tenerlo ya instalado
if(length(pkg[!instalados]) > 0) install.packages(pkg[!instalados])
installedpackages <- lapply(pkg, library, character.only=TRUE)
```

#### Algunas funciones genéricas

```{r, eval=FALSE}

# La fecha de HOY
Sys.Date()

# La fecha de AYER
Sys.Date()-1

# La fecha de hace 100 días (Incluyendo sábados y domingos)
Sys.Date()-100

# Una lista, con 3 elementos de distintos tipos de datos
Lista <- list(Numeros=c(1,2,3), Caracter="c", Fecha=Sys.Date())

# El primer integrante, va en [[ ]], del primer elemento, ya en [ ], de la lista
Lista[[1]][1]

# O utilizando los nombres de los indices, con $ indexamos por nombre.
Lista$Numeros[1]

# Visualizar la estructura y contenido de un objeto
str(Lista)

# En R y en muchos otros lenguajes, Un FOR o IF de una sola instrucción no necesita paréntesis

for(i in 1:5)
  print(i)
  
# Pero sólo es útil cuando es una sola instrucción
for(i in 1:5)
  print(i)
  print("fuera del ciclo")

# Un comando para buscar y señalar índice de elemento encontrado
OtrosNumeros <- c(15,2,35,44,55,600,71,8,9000)
which(OtrosNumeros > 50)

# Un comando para encontrar si existe al menos 1 caso TRUE
any(OtrosNumeros > 1000)

```
